### ISSUE TITLE
Require that the user accepts terms & conditions before starting to use the app

### ISSUE THREAD

**Issue by pyritewolf** [instedd/oasis#9] opened 2020-05-18 20:24 UTC
Terms & conditions are, right now, optional. They should be available during the sign up process, and accepting them should be mandatory to proceed with sign-up

**Comment by pyritewolf** [comment] 2020-05-20 13:52
@ste519 hello there! I just realized this might be a good issue for you if you happen to have the time! 😄

**Comment by easpencer** [comment] 2020-07-04 19:06
Updated and edited TC is here:
https://docs.google.com/document/d/1RrGjm1vxn2LaZj2WxpDOgQPdphHHNXVCkqolpSXSbFE

@ste519 
@pyritewolf

**Comment by ste519** [comment] 2020-07-28 15:45
Duplicate of #173

**Closed by ste519** 2020-07-28 15:45 UTC
