### ISSUE TITLE
Error after completing demographics

### ISSUE THREAD

**Issue by nditada** [instedd/oasis#81] opened 2020-06-05 16:46 UTC
Reported by  @easpencer:

> When I use guest on any device it's failing after the demographics, doesn't make it to symptoms.

![image](https://user-images.githubusercontent.com/1359189/83902527-e75c2300-a732-11ea-9c57-0ce2ebca044b.png)

**Comment by pyritewolf** [comment] 2020-06-05 20:05
Can't reproduce on staging. I suspect it had to do with #72 which has been merged & deployed.

@mmuller could you double check?

**Comment by pyritewolf** [comment] 2020-06-09 19:06
Closing it because Mauri couldn't reproduce it either!

**Closed by pyritewolf** 2020-06-09 19:06 UTC
Labels: bug

**Comment by pyritewolf** [comment] 2020-06-16 14:41
Work item deleted in Commit
